FROM node:18.18.2
WORKDIR /app

COPY package*.json ./

RUN npm install -g npm@latest
RUN npm install -g @angular/cli@^17.0.0

COPY ./docker/docker-entrypoint.local.sh /docker-entrypoint.local.sh
RUN chmod +x /docker-entrypoint.local.sh

EXPOSE 4200

ENTRYPOINT /docker-entrypoint.local.sh
